### ISSUE TITLE
white screen after click on new content element

### ISSUE THREAD

**Issue by blueamerican** [websightgmbh/typo3-ws_textmedia_bootstrap#6] opened 2016-03-25 16:16 UTC
after installation of your extension (v.2.1.0) i cannot add new content on a page:

this is all i see after click on the content button:

"Neues Inhaltselement
Wählen Sie bitte den Seiteninhaltstyp aus, den Sie erstellen wollen:"

the rest of the page is blank.

TYPO3 7.6.2
fluid_styled_responsive_images 1.1.1

**Comment by cedricziel** [comment] 2016-04-24 09:31
I cannot reproduce this. - Can you tell me more about your environment?

**Comment by Karionis** [comment] 2016-05-09 16:06
I can reproduce this:
TYPO3 7.6.6
fluid_styled_responsive_images 1.1.1
ws_textmedia_bootstrap  2.1.1

inserted static template either Bootstrap Textmedia: Replace (ws_textmedia_bootstrap) or
Bootstrap Textmedia: Standalone (ws_textmedia_bootstrap) and
basic.loadContentElementWizardTsConfig extension setting checked

When trying to create a new content element by clicking + in the normal column the following selection of type of content-element is empty.

**Comment by MrMaggo** [comment] 2016-05-17 12:21
i have the same problem:
TYPO3 7.6.6
fluid_styled_content
fluid_styled_responsive_images 1.1.1
ws_textmedia_bootstrap 2.1.1
- no content element is selectable in backend  - empty page
- all existing content elements are of type "Text & Media Bootstrap" - text & media, plugins,...
- extension adds a tab (same name as the tab in front of it - "Kategorie", "Kategorie") with "Kategorien" and "Bootstrap-Einstellungen"

... you can have an account on my test installation to see the "problem" ;-)

**Comment by cedricziel** [comment] 2016-05-24 13:21
7.6.8 / .9 seems to fix a core bug, where te TCA was shaken and the grid settings were in the wrong place.

Any chance there's something correlating? We're using the plugin in production and have 0 issues. Can you re-check with the current version?

**Comment by Karionis** [comment] 2016-05-28 17:06
It still does not work, the selection of content elements to create is empty.

I updated to TYPO3 7.6.9
fluid_styled_responsive_images V1.2.0

**Comment by cedricziel** [comment] 2016-06-08 12:43
Thx for your reports. A fix is on the way.

**Comment by cedricziel** [comment] 2016-06-08 12:47
Fixed in 378a2c2eb3701b6a1e89cd8ae6598e6f03f1ca51, I'll draft a new release later today. Thank you!

**Closed as completed by cedricziel** 2016-06-08 12:47 UTC
